version: "3.8"

services:
  ratestask-db:
    container_name: ratestask-db
    build: ratestask
    image: ratestask-db
    network_mode: host
    ports:
      - "5432:5432"
    environment:
      PGPASSWORD: "ratestask"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  ratestask-service:
    container_name: ratestask-service
    depends_on:
      ratestask-db:
        condition: service_healthy
    build: .
    image: ratestask-service
    network_mode: host
    ports:
      - "5000:5000"
    environment:
      # Should be stored as a secret
      OPEN_EX_RATES_API_KEY: "fa8bd012d91e422faf3313e657ce81a5"
