#!/bin/bash
set -euo pipefail


git submodule update --init
git submodule update

python3.8 -m venv venv

source venv/bin/activate

pip install --upgrade pip
pip install -r requirements.txt

export FLASK_APP=app/__init__.py
export FLASK_ENV=development
# Should be stored as a secret
export OPEN_EX_RATES_API_KEY=fa8bd012d91e422faf3313e657ce81a5

flask run
